name: Docker Image CI

on:
  push:
    branches: [ "v0.9.1" ]
  pull_request:
    branches: [ "v0.9.1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile1 --tag vllm-openai:v0.9.1-cu124
